### ISSUE TITLE
 An error occurs only when the 0th item is deleted.

### ISSUE THREAD

**Issue by suyeonhan** [realm/realm-android-adapters#108] opened 2017-04-18 05:14 UTC
An error occurs only when the 0th is deleted. What should I do?

#### Code

```java
public class MemoRecyclerAdapter extends RealmRecyclerViewAdapter<Memo, MemoRecyclerAdapter.ViewHolder> {

    private Context mContext;
    private TextView mMemoTextView;

    public void delete(int adapterPosition) {
        Realm realm = Realm.getDefaultInstance();
        realm.beginTransaction();
        Memo memo = getItem(adapterPosition);
        memo.deleteFromRealm();
        realm.commitTransaction();
        realm.close();
    }
```

#### Stack Trace

```java

04-18 14:06:18.521 17580-17580/com.todolist.suyeonh.todolist E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.todolist.suyeonh.todolist, PID: 17580
                                                                               java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 0(offset:-1).state:4
                                                                                   at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5458)
                                                                                   at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5394)
                                                                                   at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5390)
                                                                                   at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
                                                                                   at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1533)
                                                                                   at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
                                                                                   at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:603)
                                                                                   at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3488)
                                                                                   at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3264)
                                                                                   at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3798)
                                                                                   at android.view.View.layout(View.java:18010)
                                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5911)
                                                                                   at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
                                                                                   at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                                   at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1375)
                                                                                   at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:870)
                                                                                   at android.view.View.layout(View.java:18010)
                                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5911)
                                                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                                   at android.view.View.layout(View.java:18010)
                                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5911)
                                                                                   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                                   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                   at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                   at android.view.View.layout(View.java:18010)
                                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5911)
                                                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                                   at android.view.View.layout(View.java:18010)
                                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5911)
                                                                                   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                                   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                   at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                   at android.view.View.layout(View.java:18010)
                                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5911)
                                                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                                   at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:3175)
                                                                                   at android.view.View.layout(View.java:18010)
                                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5911)
                                                                                   at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2784)
                                                                                   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2477)
                                                                                   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1544)
                                                                                   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7616)
                                                                                   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                                                                                   at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                                   at android.view.Choreographer.doFrame(Choreographer.java:622)
                                                                                   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:7406)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                               	at com.android.internal.os.ZygoteIn

```

#### Version of Realm and tooling
Realm version(s): 3.0

Android Studio version: 2.3.1

Which Android version and device: Samsung Note 5

**Comment by beeender** [comment] 2017-04-18 06:49
Please update the realm-java to `v3.1.2`, this should be fixed already.

**Comment by suyeonhan** [comment] 2017-04-18 07:19
I updated and still get an error

**Comment by beeender** [comment] 2017-04-18 08:02
@suyeonhan Have you ever call `notifyXxxChanged` method in any other places by yourself?

**Comment by suyeonhan** [comment] 2017-04-18 08:09
I do not use notifyXxxChanged method

**Comment by beeender** [comment] 2017-04-18 08:24
@suyeonhan Then i have no idea... can you share your project with us? to help@realm.io if you want to share it privately.

**Comment by suyeonhan** [comment] 2017-04-18 08:44
OK. I'll send you mail.

**Comment by beeender** [comment] 2017-04-18 09:16
The problem is you have `setHasStableIds(true);` in your `MemoRecyclerAdapter`. But actually the the `RealmRecyclerViewAdapter.getItemId()` won't return a stable ID.
See the java doc of the function:
>   /**
     * Returns the current ID for an item. Note that item IDs are not stable so you cannot rely on the item ID being the
     * same after notifyDataSetChanged() or {@link #updateData(OrderedRealmCollection)} has been called.
     *
     * #param index position of item in the adapter.
     * #return current item ID.
     */

**Comment by suyeonhan** [comment] 2017-04-19 01:23
I solved the problem. Thank you. ;)

**Comment by beeender** [comment] 2017-04-19 01:59
YEAH 🍻

**Closed by beeender** 2017-04-19 01:59 UTC
Labels: T:Help
