### ISSUE TITLE
Method "onChanged()" of RecyclerView.AdapterDataObserver isn't being called

### ISSUE THREAD

**Issue by marc97** [realm/realm-android-adapters#122] opened 2017-05-21 01:08 UTC
I have a ```RecyclerViewRealmAdapter``` registering a ```RecyclerView.AdapterDataObserver```, but ```onChanged()``` is never fired when an item is inserted/removed in realm. 
I've tested it using the default ```RecyclerView.Adapter``` and works perfectly. 

``` java
final RecyclerView.Adapter<?> adapter = mRecyclerView.getAdapter();
RecyclerView.AdapterDataObserver emptyObserver = new RecyclerView.AdapterDataObserver() {
        @Override
        public void onChanged() {
            // Not called
        }
};
adapter.registerAdapterDataObserver(emptyObserver); 
```

> Versions used: 
> 'io.realm:realm-gradle-plugin:3.1.4' 
> 'io.realm:android-adapters:2.0.0'

**Comment by zaki50** [comment] 2017-05-25 18:07
I guess `RecyclerView.AdapterDataObserver.onItemRangeInserted()` or  `RecyclerView.AdapterDataObserver.onItemRangeRemoved()` is called instead of `RecyclerView.AdapterDataObserver.onChanged()`.

Could you check those methods as well?

Recent `RecyclerViewRealmAdapter` calles `RecyclerView.Adapter.notifyItemRangeInserted()` or `RecyclerView.Adapter.notifyItemRangeRemoved()` instead of `RecyclerView.Adapter.notifyDataSetChanged()` and `notifyItemRangeInserted()` and `notifyItemRangeRemoved()` does not trigger `onChanged()`.

**Comment by ni032mas** [comment] 2017-05-29 15:25
I have the same problem. I checked, instead of `RecyclerView.AdapterDataObserver.onChanged()`, called `RecyclerView.AdapterDataObserver.onItemRangeInserted()`  or `RecyclerView.AdapterDataObserver.onItemRangeRemoved()`.

**Comment by zaki50** [comment] 2017-05-29 18:25
@ni032mas That's the intended behavior. Why is that the problem?

**Comment by marc97** [comment] 2017-05-29 19:02
@zaki50 I've checked the methods `RecyclerView.AdapterDataObserver.onItemRangeInserted(` and `RecyclerView.AdapterDataObserver.onItemRangeRemoved()` and both works well. This issue can be closed.

**Comment by ni032mas** [comment] 2017-05-29 19:10
I had a problem, now it's not there )

**Comment by dalinaum** [comment] 2017-06-01 06:23
@marc97 It's good to hear that your problem is resolved, I will close this issue.

**Closed by dalinaum** 2017-06-01 06:23 UTC
Labels: T:Help

**Comment by rubenwardy** [comment] 2017-08-31 16:23
> That's the intended behavior. Why is that the problem?

Why is it intended behaviour? Surely the onChanged callback should be called whenever the data changes?

**Comment by zaki50** [comment] 2017-08-31 22:34
@rubenwardy To achieve correct animation on RecyclerView, more fine-grained callback than `onChanged ()` should be called.

**Comment by DenizBabat** [comment] 2022-11-29 10:45
```
class foo: Fragment{

private val documentRecyclerView get() = dataBinding.documentRecyclerView

private fun manipulateRecyclerViewScroll(){
        lifecycleScope.launchWhenResumed {
            documentRecyclerView.doOnPreDraw {
                documentRecyclerView.adapter!!.registerAdapterDataObserver(object :
                    RecyclerView.AdapterDataObserver() {
                    override fun onItemRangeChanged(positionStart: Int, itemCount: Int) {
                        super.onItemRangeChanged(positionStart, itemCount)
                        documentRecyclerView.scrollToPosition(0)
                    }
                })
            }
        }
    }
}
```
